"""empty message

Revision ID: ad73c1f79731
Revises: 12e0aeffb8ca
Create Date: 2021-06-06 15:34:54.197578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad73c1f79731'
down_revision = '12e0aeffb8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.drop_column('artist', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_venues')
    # ### end Alembic commands ###
